const state = { stats: null, reports: [], alerts: [], actions: [], sites: [], activities: [], rules: [] };
const api = async (path, options = {}) => { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error((await response.json()).detail || 'Request failed'); return response.json() };
const $ = id => document.getElementById(id); const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
function showLoading(on) { $('loading').classList.toggle('show', on) }
function formatDate(value) { return value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' }) : '—' }
function rankMarkup(items, limit = 5) { const max = Math.max(...items.map(item => item.density), 1); return items.slice(0, limit).map((item, index) => `<div class="ranking-item"><span class="rank">0${index + 1}</span><div><strong>${esc(item.name)}</strong><div class="bar-track"><div class="bar-fill" style="width:${Math.max(5, item.density / max * 100)}%"></div></div></div><span class="rank-value">${item.density}%</span></div>`).join('') || '<div class="empty-state">No data yet</div>' }
async function loadData() { showLoading(true); try { [state.stats, state.reports, state.alerts, state.actions, state.sites, state.activities, state.rules] = await Promise.all([api('/dashboard/stats'), api('/reports/?limit=100'), api('/alerts/'), api('/actions/'), api('/dashboard/top-sites'), api('/dashboard/top-activities'), api('/dashboard/top-rules')]); renderAll() } catch (error) { console.error(error); $('loading').textContent = 'API unavailable. Start FastAPI to load live data.'; $('loading').classList.add('show') } finally { setTimeout(() => showLoading(false), 500) } }
function renderAll() { const s = state.stats || {}; $('total-reports').textContent = s.total_reports ?? 0; $('sif-reports').textContent = s.sif_reports ?? 0; $('non-sif-reports').textContent = s.non_sif_reports ?? 0; $('high-alerts').textContent = s.high_risk_alerts ?? 0; $('sif-rate').textContent = `${s.sif_percentage ?? 0}% of all reports`; $('alert-count').textContent = s.high_risk_alerts ?? 0; $('site-ranking').innerHTML = rankMarkup(state.sites); $('precursor-sites').innerHTML = rankMarkup(state.sites, 10); $('activity-ranking').innerHTML = rankMarkup(state.activities); $('precursor-list').innerHTML = state.rules.slice(0, 4).map(rule => `<div class="precursor"><strong>${esc(rule.name)}</strong>${rule.sif_reports} SIF signals across ${rule.reports} reports (${rule.density}%)</div>`).join('') || '<div class="empty-state">No patterns yet</div>'; renderReports(); renderAlerts(); renderActions(); drawCharts() }
function renderReports() { const query = ($('report-search')?.value || '').toLowerCase(); const risk = $('risk-filter')?.value || ''; const filtered = state.reports.filter(r => (!risk || r.risk_level === risk) && (!query || `${r.report_text} ${r.location} ${r.activity}`.toLowerCase().includes(query))); $('reports-table').innerHTML = filtered.map(r => `<tr><td><strong>${esc(r.report_text)}</strong><span class="muted">${esc(r.report_type)} · ${formatDate(r.created_at)}</span></td><td>${esc(r.location)}</td><td>${esc(r.life_saving_rule)}</td><td><span class="badge ${r.risk_level.toLowerCase()}">${esc(r.risk_level)} · ${Math.round(r.sif_probability * 100)}%</span></td><td>${esc(r.status)}</td></tr>`).join('') || '<tr><td colspan="5" class="empty-state">No reports match this filter.</td></tr>' }
function renderAlerts() { $('alerts-grid').innerHTML = state.alerts.map(a => `<article class="alert-card"><span class="badge high">${esc(a.severity)} PRIORITY</span><h3>${esc(a.report.activity)} · ${esc(a.report.location)}</h3><p>${esc(a.report.report_text)}</p><div class="alert-meta"><span>${esc(a.report.life_saving_rule)}</span><span>${formatDate(a.created_at)}</span><span>${esc(a.status)}</span></div></article>`).join('') || '<div class="panel empty-state">No high-risk alerts. New signals will appear here.</div>' }
function renderActions() { $('actions-table').innerHTML = state.actions.map(a => `<tr><td><strong>${esc(a.description)}</strong></td><td>${esc(a.responsible)}</td><td><span class="badge ${a.priority.toLowerCase()}">${esc(a.priority)}</span></td><td>${formatDate(a.due_date)}</td><td><span class="badge ${a.status === 'Completed' ? 'done' : ''}">${esc(a.status)}</span></td></tr>`).join('') || '<tr><td colspan="5" class="empty-state">No corrective actions have been logged.</td></tr>' }
let trendChart, rulesChart; async function drawCharts() { try { const trend = await api('/dashboard/sif-trend'); if (trendChart) trendChart.destroy(); trendChart = new Chart($('trend-chart'), { type: 'line', data: { labels: trend.map(x => x.date), datasets: [{ label: 'SIF potential', data: trend.map(x => x.sif_reports), borderColor: '#13795b', backgroundColor: 'rgba(19,121,91,.1)', fill: true, tension: .35 }, { label: 'All reports', data: trend.map(x => x.reports), borderColor: '#b7c7c0', borderDash: [4, 4], tension: .35 }] }, options: { responsive: true, plugins: { legend: { position: 'bottom', labels: { boxWidth: 10, usePointStyle: true } } }, scales: { y: { beginAtZero: true, grid: { color: '#edf2ef' } }, x: { grid: { display: false }, ticks: { maxTicksLimit: 8 } } } } }); if (rulesChart) rulesChart.destroy(); rulesChart = new Chart($('rules-chart'), { type: 'doughnut', data: { labels: state.rules.slice(0, 6).map(x => x.name), datasets: [{ data: state.rules.slice(0, 6).map(x => x.sif_reports), backgroundColor: ['#13795b', '#e39b2f', '#d65b4b', '#3b7b89', '#8a9b53', '#bd7861'], borderWidth: 0 }] }, options: { cutout: '68%', plugins: { legend: { position: 'bottom', labels: { boxWidth: 10, usePointStyle: true, padding: 12 } } } } }) } catch (error) { console.error(error) } }
function navigate(view) { document.querySelectorAll('.view').forEach(el => el.classList.remove('active-view')); $(`view-${view}`).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach(el => el.classList.toggle('active', el.dataset.view === view)); $('page-title').textContent = { overview: 'Executive overview', analyzer: 'AI report analyzer', reports: 'Safety reports', alerts: 'SIF alerts', precursors: 'Precursor analysis', actions: 'Corrective actions' }[view] }
document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => navigate(button.dataset.view))); document.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => navigate(button.dataset.go))); $('report-search').addEventListener('input', renderReports); $('risk-filter').addEventListener('change', renderReports);
$('analysis-form').addEventListener('submit', async event => { event.preventDefault(); const error = $('analysis-error'); error.textContent = ''; const button = event.target.querySelector('button'); button.disabled = true; button.textContent = 'Analyzing...'; try { const result = await api('/analysis/', { method: 'POST', body: JSON.stringify({ report_text: $('report-text').value, report_type: $('report-type').value, location: $('location').value, department: $('department').value, activity: $('activity').value, persist: true }) }); $('analysis-result').classList.remove('empty'); $('analysis-result').innerHTML = `<span class="result-kicker">MODEL ASSESSMENT · ${esc(result.sif_label)}</span><div class="result-title ${result.risk_level.toLowerCase()}">${esc(result.risk_level)} RISK</div><div class="result-score">SIF confidence <strong>${Math.round(result.sif_probability * 100)}%</strong></div><div class="result-details"><div class="detail"><span>Life-Saving Rule</span><strong>${esc(result.life_saving_rule)}</strong></div><div class="detail"><span>Activity</span><strong>${esc(result.activity)}</strong></div><div class="detail"><span>Barrier failure</span><strong>${esc(result.barrier_failure)}</strong></div><div class="detail"><span>Potential consequence</span><strong>${esc(result.potential_consequence)}</strong></div></div><p>${esc(result.explanation)}</p>`; await loadData() } catch (e) { error.textContent = e.message } finally { button.disabled = false; button.textContent = '✦ Analyze and save report' } });
loadData();
